name: Update README2

on:
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update profile README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Update README with recent activity
        uses: RafaAlcantar/RafaAlcantar@main # Reemplaza con tu información
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
